### ISSUE TITLE
Add support for OpenAPI v3

### ISSUE THREAD

**Issue by Tobion** [Tobion/OpenAPI-Symfony-Routing#4]
Add compatiblity with v3 of https://github.com/zircote/swagger-php. In bast case it should be compatible with v2 and v3 at the same time without any outside change needed.

**Comment by Tobion** [comment]
For documenting v2 and v3 examples of annotations with markdown it might be best to use side-by-side table columns with collapsable `<details>`

<table>
    <tbody>
        <tr>
            <td>
<details open>
    <summary>OpenAPI v3</summary>

```php
use Swagger\Annotations as SWG;

/**
 * @SWG\Swagger(
 *     @SWG\Info(title="My API", version="1.0")
 * )
 */
class MyController
{
    /**
     * @SWG\Get(
     *     path="/foobar",
     *     @SWG\Response(response="200", description="Success")
     * )
     */
    public function __invoke()
    {
    }
}
```

</details>
            </td>
            <td>
<details>
    <summary>OpenAPI v2</summary>

```php
use Swagger\Annotations as SWG;

/**
 * @SWG\Swagger(
 *     @SWG\Info(title="My API", version="1.0")
 * )
 */
class MyController
{
    /**
     * @SWG\Get(
     *     path="/foobar",
     *     @SWG\Response(response="200", description="Success")
     * )
     */
    public function __invoke()
    {
    }
}
```

</details>
            </td>
        </tr>
    </tbody>
</table>

**Comment by kswzr** [comment]
Hey! Doesn't really know, if we should have both versions existent in a new release. v2 users can use v1 of this package.
